### ISSUE TITLE
Use fmin and fmax in min, max, and clamp library routines

### ISSUE THREAD

**Issue by bradgrantham** [bradgrantham/earwig_vulkan#11]

**Comment by bradgrantham** [comment]
Unless Lawrence implements #10 first

**Comment by lkesteloot** [comment]
Bug #10 is fixed, so I think this is now: delete `.min` and `.max`, use fmin.s and fmax.s in `.clamp`?

**Comment by lkesteloot** [comment]
Fixed by 3598ac7
