### ISSUE TITLE
Fix multi-threaded crash in sim

### ISSUE THREAD

**Issue by lkesteloot** [bradgrantham/earwig_vulkan#17]

**Comment by lkesteloot** [comment]
If I modify the file `$HOME/share/verilator/include/verilated.mk` so that this line:

    CFG_CXXFLAGS_STD_NEWEST = -std=gnu++14

instead says:

    CFG_CXXFLAGS_STD_NEWEST = -std=c++17

then it doesn't crash. I don't know how to modify that variable from our own Makefile. Looks like it's set by `configure.ac` at install time. It must have mistakenly picked an older GNU revision.

**Comment by lkesteloot** [comment]
Oh you also have to pass `--threads 1` to verilator.

**Comment by bradgrantham** [comment]
I just installed to the default location, so I had to edit /usr/local/share/verilator/include/verilated.mk.

**Comment by bradgrantham** [comment]
I put this information in the wiki at https://github.com/bradgrantham/earwig_vulkan/wiki
