### ISSUE TITLE
Implement rounding mode in float-to-int

### ISSUE THREAD

**Issue by bradgrantham** [bradgrantham/earwig_vulkan#9]
In creation.frag and wavy.frag, at least one occurrence of fcvt.x.s uses rdn rounding mode, so that (in one example) bf657064(-0.896246) should become -1.  Currently it becomes 0.

Several library routines use rdn to implement floor.

gpuemu uses rint(), which uses the rounding mode set through fesetround().

Perhaps add a rounding mode through rmode like fpu.v does, but at the moment I don't think library.s uses "rup".  It does use "rtx", "rne", and "rdn".

**Comment by lkesteloot** [comment]
Sorry I don't understand this bug. What is "float-to-int"?

**Comment by bradgrantham** [comment]
Is fpu/float-to-int.v yours?

**Comment by bradgrantham** [comment]
Fixed in 4344768ba4efbc7a1851ac5cbd9eb3491b6280e0
